services:
  app:
    container_name: menuco-app
    image: menuco-app:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - ./public/build:/var/www/public/build
      - ./storage:/var/www/storage
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: menuco-nginx
    image: menuco-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public:ro
      - ./storage/app/public:/var/www/storage:ro
    ports:
      - "8000:3001"
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://nginx:3001" ]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: mysql:8.0
    container_name: menuco-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:Z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u ${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
    mysql_data:
